### ISSUE TITLE
Ergänze Hochschulgruppenstatus

### ISSUE THREAD

**Issue by azrdev** [ChaosDarmstadt/chaos-darmstadt.de#15]
ATM weisen wir nicht mal mehr im Impressum darauf hin, eine Hochschulgruppe zu sein. Soll das so?

**Comment by psy** [comment]
Unter "Unterstützen" weißen wir drauf hin: https://www.chaos-darmstadt.de/unterstuetzen.html

**Comment by azrdev** [comment]
nvm
