### ISSUE TITLE
Anfahrtsinfos fehlen

### ISSUE THREAD

**Issue by okin** [ChaosDarmstadt/chaos-darmstadt.de#4]
Es wäre super, wenn irgendwo die Möglichkeiten zur Anfahrt beschrieben werden.
Ich denke man sollte auf Anreise mit dem Auto, Fahrrad und öffentlichen Verkehrsmitteln eingehen.

Mein Vorschlag wäre das ganze im Bereich _Hackspace_ zu realisieren, weil ich es dort als erstes suchen würde.

**Comment by mweinelt** [comment]
10/10 würde auf die Seite werfen.
Los Okin, du bist dran!
